{% set name = "orocos-kdl" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/orocos/orocos_kinematics_dynamics/archive/v{{ version }}.tar.gz
  sha256: 5acb90acd82b10971717aca6c17874390762ecdaa3a8e4db04984ea1d4a2af9b
  patches:
    - python_orocos_kdl.patch
    - remove_version_symlinks.patch 

build:
  number: 7

outputs:
  - name: orocos-kdl
    version: {{ version }}
    script: buildpkg.sh  # [unix]
    script: bldpkg.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('orocos-kdl', max_pin='x.x') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja       # [win]
        - make        # [not win]
        - pkg-config      
      host:
        - eigen
      run:
        - eigen
    test:
      commands:
        - if not exist %LIBRARY_PREFIX%\\lib\\orocos-kdl.lib exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\orocos-kdl.dll exit 1  # [win]
        - test -f $PREFIX/lib/liborocos-kdl${SHLIB_EXT}              # [unix]
  - name: python-orocos-kdl
    version: {{ version }}
    script: buildpkg.sh  # [unix]
    script: bldpkg.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('python-orocos-kdl', max_pin='x.x') }}
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
        - cmake
        - ninja                                  # [win]
        - make                                   # [not win]
        - pkg-config
      host:
        - python
        - eigen
        - orocos-kdl
        - pybind11
      run:
        - python
        - eigen
        - orocos-kdl
        - pybind11
    test:
      imports:
        - PyKDL
      commands:
        - python -c "from PyKDL import Joint; j = Joint('test')"

about:
  home: https://github.com/orocos/orocos_kinematics_dynamics
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: orocos_kdl/COPYING
  summary: |
    Orocos Kinematics and Dynamics C++ library

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
