{% set name = "orocos-kdl" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/orocos/orocos_kinematics_dynamics/archive/v{{ version }}.tar.gz
  sha256: 05b93e759923684dc07433ccae1e476d158d89b3c2be5079c20062406da7b4dd
  patches:
    - orocos_kdl.patch
    - python_orocos_kdl.patch
    - python_osx.patch  # [osx]

build:
  number: 0
  skip: true  # [win and vc<14]
  script: "echo 'do nothing'"  # [unix]
  run_exports:
    - {{ pin_subpackage('orocos-kdl', max_pin='x.x') }}
    - {{ pin_subpackage('python-orocos-kdl', max_pin='x.x') }}

outputs:
  - name: orocos-kdl
    version: {{ version }}
    script: buildpkg.sh  # [unix]
    script: bldpkg.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja  # [win]
        - make  # [not win]
        - pkg-config
      host:
        - eigen
      run:
        - eigen
    test:
      commands:
        - if not exist %LIBRARY_PREFIX%\\lib\\orocos-kdl.lib exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\\lib\\orocos-kdl.dll exit 1  # [win]
        - test -f $PREFIX/lib/liborocos-kdl${SHLIB_EXT}  # [unix]
  - name: python-orocos-kdl
    version: {{ version }}
    script: buildpkg.sh  # [unix]
    script: bldpkg.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - cmake
        - ninja  # [win]
        - make  # [not win]
        - pkg-config
      host:
        - python
        - eigen
        - orocos-kdl
        - sip 4.19.20  # [win]
        - sip  # [not win]
      run:
        - python
        - eigen
        - orocos-kdl
        - sip 4.19.20  # [win]
        - sip  # [not win]
    test:
      imports:
        - PyKDL

about:
  home: https://github.com/orocos/orocos_kinematics_dynamics
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: orocos_kdl/COPYING
  summary: |
    Orocos Kinematics and Dynamics C++ library

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
